import { createSlice } from "@reduxjs/toolkit";

const initialId = () => {
  const init = window.localStorage.getItem("threadId");
  return JSON.parse(init);
};

const initialState = {
  allTickets: [],
  threadMessage: [],
  threadId: initialId(),
  contacts: [
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Amalinda",
      email: "dndhelpdesk@gmail.com",
      phone: "0000 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Amanzimtoti",
      email: "dndhelpdesk@gmail.com",
      phone: "1 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Arbour Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "2 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Arcadia",
      email: "dndhelpdesk@gmail.com",
      phone: "3 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Athlone",
      email: "dndhelpdesk@gmail.com",
      phone: "4 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Atteridgeville",
      email: "dndhelpdesk@gmail.com",
      phone: "5 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Avonwood Square",
      email: "dndhelpdesk@gmail.com",
      phone: "6 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Ballito",
      email: "dndhelpdesk@gmail.com",
      phone: "7 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Beach Front East London",
      email: "dndhelpdesk@gmail.com",
      phone: "8 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Beaufort West",
      email: "dndhelpdesk@gmail.com",
      phone: "9 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Bellville Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "10 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Benmore Gardens",
      email: "dndhelpdesk@gmail.com",
      phone: "11 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Birch Acres Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "12 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Blue Downs",
      email: "dndhelpdesk@gmail.com",
      phone: "13 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Boksburg Key Largo",
      email: "dndhelpdesk@gmail.com",
      phone: "14 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Bothasig",
      email: "dndhelpdesk@gmail.com",
      phone: "15 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Boulders",
      email: "dndhelpdesk@gmail.com",
      phone: "16 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Brackencity",
      email: "dndhelpdesk@gmail.com",
      phone: "17 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Bronkhorstspruit",
      email: "dndhelpdesk@gmail.com",
      phone: "18 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Caltex Fortgale Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "19 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Caltex Maclear",
      email: "dndhelpdesk@gmail.com",
      phone: "20 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Caltex Malelane",
      email: "dndhelpdesk@gmail.com",
      phone: "21 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Caltex Naboomspruit",
      email: "dndhelpdesk@gmail.com",
      phone: "22 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Caltex Northcrest",
      email: "dndhelpdesk@gmail.com",
      phone: "23 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Carletonville",
      email: "dndhelpdesk@gmail.com",
      phone: "24 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Carolina",
      email: "dndhelpdesk@gmail.com",
      phone: "25 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Celtis Ridge",
      email: "dndhelpdesk@gmail.com",
      phone: "26 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Centurion Lifestyle",
      email: "dndhelpdesk@gmail.com",
      phone: "27 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Chuma Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "28 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Cradlestone Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "29 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Die Bult",
      email: "dndhelpdesk@gmail.com",
      phone: "30 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Dowerglen",
      email: "dndhelpdesk@gmail.com",
      phone: "31 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Dundee Caltex",
      email: "dndhelpdesk@gmail.com",
      phone: "32 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Dunoon",
      email: "dndhelpdesk@gmail.com",
      phone: "33 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Durbanville",
      email: "dndhelpdesk@gmail.com",
      phone: "34 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Eldoraigne",
      email: "dndhelpdesk@gmail.com",
      phone: "35 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Bisho",
      email: "dndhelpdesk@gmail.com",
      phone: "36 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Bluewater Bay PE",
      email: "dndhelpdesk@gmail.com",
      phone: "37 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Ikwezi N2 Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "38 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Ngwelezane",
      email: "dndhelpdesk@gmail.com",
      phone: "39 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Nseleni",
      email: "dndhelpdesk@gmail.com",
      phone: "40 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Nyala",
      email: "dndhelpdesk@gmail.com",
      phone: "41 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Pretoria Motors",
      email: "dndhelpdesk@gmail.com",
      phone: "42 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Queensburgh",
      email: "dndhelpdesk@gmail.com",
      phone: "43 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Engen Tembisa",
      email: "dndhelpdesk@gmail.com",
      phone: "44 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Escombe",
      email: "dndhelpdesk@gmail.com",
      phone: "45 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Florida Road",
      email: "dndhelpdesk@gmail.com",
      phone: "46 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Fochville",
      email: "dndhelpdesk@gmail.com",
      phone: "47 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Ga-Rankuwa",
      email: "dndhelpdesk@gmail.com",
      phone: "48 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Galleria",
      email: "dndhelpdesk@gmail.com",
      phone: "49 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Germiston Station Bazaar Express",
      email: "dndhelpdesk@gmail.com",
      phone: "50 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Gezina",
      email: "dndhelpdesk@gmail.com",
      phone: "51 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Giyani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "52 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Giyani Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "53 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Glen Village (Faerie Glen)",
      email: "dndhelpdesk@gmail.com",
      phone: "54 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Grassy Park",
      email: "dndhelpdesk@gmail.com",
      phone: "55 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Grey Street Express",
      email: "dndhelpdesk@gmail.com",
      phone: "56 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Greytown",
      email: "dndhelpdesk@gmail.com",
      phone: "57 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Groblersdal",
      email: "dndhelpdesk@gmail.com",
      phone: "58 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Groblersdal Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "59 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Grosvenor Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "60 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Gugulethu",
      email: "dndhelpdesk@gmail.com",
      phone: "61 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Hammarsdale Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "62 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Heidelberg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "63 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Highland Mews",
      email: "dndhelpdesk@gmail.com",
      phone: "64 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Isipingo",
      email: "dndhelpdesk@gmail.com",
      phone: "65 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Ixopo",
      email: "dndhelpdesk@gmail.com",
      phone: "66 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Junction 14",
      email: "dndhelpdesk@gmail.com",
      phone: "67 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kaalfontein",
      email: "dndhelpdesk@gmail.com",
      phone: "68 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kagiso Shopping Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "69 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kensington",
      email: "dndhelpdesk@gmail.com",
      phone: "70 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Khayelitsha",
      email: "dndhelpdesk@gmail.com",
      phone: "71 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kidds Beach",
      email: "dndhelpdesk@gmail.com",
      phone: "72 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Klapmuts",
      email: "dndhelpdesk@gmail.com",
      phone: "73 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Klerksdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "74 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Knysna",
      email: "dndhelpdesk@gmail.com",
      phone: "75 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kokstad",
      email: "dndhelpdesk@gmail.com",
      phone: "76 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Komatipoort",
      email: "dndhelpdesk@gmail.com",
      phone: "77 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kriel",
      email: "dndhelpdesk@gmail.com",
      phone: "78 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kromboom",
      email: "dndhelpdesk@gmail.com",
      phone: "79 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Krugersdorp Paardekraal",
      email: "dndhelpdesk@gmail.com",
      phone: "80 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kuilsrivier",
      email: "dndhelpdesk@gmail.com",
      phone: "81 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kwa Guqa",
      email: "dndhelpdesk@gmail.com",
      phone: "82 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kwagga Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "83 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza KwaMnyandu Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "84 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Kwamsane",
      email: "dndhelpdesk@gmail.com",
      phone: "85 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Lemo Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "86 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Lichtenburg",
      email: "dndhelpdesk@gmail.com",
      phone: "87 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Lusikisiki",
      email: "dndhelpdesk@gmail.com",
      phone: "88 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mabopane Square",
      email: "dndhelpdesk@gmail.com",
      phone: "89 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Macassar",
      email: "dndhelpdesk@gmail.com",
      phone: "90 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mall at Carnival",
      email: "dndhelpdesk@gmail.com",
      phone: "91 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mall Of The North",
      email: "dndhelpdesk@gmail.com",
      phone: "92 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mall Of the South",
      email: "dndhelpdesk@gmail.com",
      phone: "93 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Malvern",
      email: "dndhelpdesk@gmail.com",
      phone: "94 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mamms Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "95 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mandini",
      email: "dndhelpdesk@gmail.com",
      phone: "96 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Masingita Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "97 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Matatiele",
      email: "dndhelpdesk@gmail.com",
      phone: "98 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Maunde Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "99 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mayibuye",
      email: "dndhelpdesk@gmail.com",
      phone: "100 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Meerensee",
      email: "dndhelpdesk@gmail.com",
      phone: "101 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mega City Mmabatho",
      email: "dndhelpdesk@gmail.com",
      phone: "102 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Meyerton",
      email: "dndhelpdesk@gmail.com",
      phone: "103 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mhluzi Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "104 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Middelburg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "105 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Middelburg Wonderpark Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "106 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Middestad",
      email: "dndhelpdesk@gmail.com",
      phone: "107 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Midwater",
      email: "dndhelpdesk@gmail.com",
      phone: "108 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Montague Gardens",
      email: "dndhelpdesk@gmail.com",
      phone: "109 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Montclair",
      email: "dndhelpdesk@gmail.com",
      phone: "110 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Moreleta",
      email: "dndhelpdesk@gmail.com",
      phone: "111 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Mossel Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "112 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza New Market",
      email: "dndhelpdesk@gmail.com",
      phone: "113 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza New Street Grahamstown",
      email: "dndhelpdesk@gmail.com",
      phone: "114 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Newcastle Corner",
      email: "dndhelpdesk@gmail.com",
      phone: "115 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Nigel",
      email: "dndhelpdesk@gmail.com",
      phone: "116 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza North Beach",
      email: "dndhelpdesk@gmail.com",
      phone: "117 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Nquthu Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "118 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Olievenhout Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "119 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Orkney",
      email: "dndhelpdesk@gmail.com",
      phone: "120 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Owen Street",
      email: "dndhelpdesk@gmail.com",
      phone: "121 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Oxford Street",
      email: "dndhelpdesk@gmail.com",
      phone: "122 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Park Square Vanderbijlpark",
      email: "dndhelpdesk@gmail.com",
      phone: "123 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Philippi",
      email: "dndhelpdesk@gmail.com",
      phone: "124 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Pinetown",
      email: "dndhelpdesk@gmail.com",
      phone: "125 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Plettenberg Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "126 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Plumstead",
      email: "dndhelpdesk@gmail.com",
      phone: "127 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza PnP Soshanguve",
      email: "dndhelpdesk@gmail.com",
      phone: "128 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Polofields",
      email: "dndhelpdesk@gmail.com",
      phone: "129 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Pongola",
      email: "dndhelpdesk@gmail.com",
      phone: "130 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Potchefstroom",
      email: "dndhelpdesk@gmail.com",
      phone: "131 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Princess Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "132 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Promenade Shopping Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "133 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Queenswood",
      email: "dndhelpdesk@gmail.com",
      phone: "134 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Raisethorpe",
      email: "dndhelpdesk@gmail.com",
      phone: "135 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Randburg Bram Fischer",
      email: "dndhelpdesk@gmail.com",
      phone: "136 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Randfontein",
      email: "dndhelpdesk@gmail.com",
      phone: "137 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Richards Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "138 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Richmond",
      email: "dndhelpdesk@gmail.com",
      phone: "139 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Riverside Square",
      email: "dndhelpdesk@gmail.com",
      phone: "140 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Rondebosch",
      email: "dndhelpdesk@gmail.com",
      phone: "141 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Rosetenville",
      email: "dndhelpdesk@gmail.com",
      phone: "142 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sarnia",
      email: "dndhelpdesk@gmail.com",
      phone: "143 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sasol Delmas",
      email: "dndhelpdesk@gmail.com",
      phone: "144 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sasol Kinross",
      email: "dndhelpdesk@gmail.com",
      phone: "145 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Shayandima",
      email: "dndhelpdesk@gmail.com",
      phone: "146 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Shell Hendrina",
      email: "dndhelpdesk@gmail.com",
      phone: "147 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Shell Isipingo",
      email: "dndhelpdesk@gmail.com",
      phone: "148 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Shell Ultra City Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "149 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Shell Voorbaai",
      email: "dndhelpdesk@gmail.com",
      phone: "150 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Silveroaks",
      email: "dndhelpdesk@gmail.com",
      phone: "151 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sky City Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "152 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Smith Street",
      email: "dndhelpdesk@gmail.com",
      phone: "153 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Somerset Mall Foodcourt",
      email: "dndhelpdesk@gmail.com",
      phone: "154 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Springs Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "155 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Stellenbosch Die Boord",
      email: "dndhelpdesk@gmail.com",
      phone: "156 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Stellenbosch Stelmark Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "157 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sun City",
      email: "dndhelpdesk@gmail.com",
      phone: "158 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sunninghill - Chilli Lane",
      email: "dndhelpdesk@gmail.com",
      phone: "159 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Sunnyside",
      email: "dndhelpdesk@gmail.com",
      phone: "160 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tembi Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "161 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tembisa Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "162 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Thavhani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "163 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza The Colony",
      email: "dndhelpdesk@gmail.com",
      phone: "164 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza The Islands Food Court",
      email: "dndhelpdesk@gmail.com",
      phone: "165 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Thohoyandou Venda Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "166 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Three Rivers",
      email: "dndhelpdesk@gmail.com",
      phone: "167 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tibani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "168 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tokai",
      email: "dndhelpdesk@gmail.com",
      phone: "169 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Total Cradock",
      email: "dndhelpdesk@gmail.com",
      phone: "170 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Total Hluhluwe",
      email: "dndhelpdesk@gmail.com",
      phone: "171 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Total Morula",
      email: "dndhelpdesk@gmail.com",
      phone: "172 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Total Rangeview Krugersdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "173 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Town Centre Express",
      email: "dndhelpdesk@gmail.com",
      phone: "174 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tshwane Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "175 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Twin City",
      email: "dndhelpdesk@gmail.com",
      phone: "176 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Tzaneen Lifestyle",
      email: "dndhelpdesk@gmail.com",
      phone: "177 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Umgeni Business Park",
      email: "dndhelpdesk@gmail.com",
      phone: "178 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Umhlanga Lagoon Drive",
      email: "dndhelpdesk@gmail.com",
      phone: "179 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Umphakathi Mall Randfontein",
      email: "dndhelpdesk@gmail.com",
      phone: "180 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vaal Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "181 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vanderbijlpark",
      email: "dndhelpdesk@gmail.com",
      phone: "182 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vangate Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "183 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vincent Park",
      email: "dndhelpdesk@gmail.com",
      phone: "184 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vorna Valley Midway Mews",
      email: "dndhelpdesk@gmail.com",
      phone: "185 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Vredendal",
      email: "dndhelpdesk@gmail.com",
      phone: "186 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Watercrest Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "187 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Watergate",
      email: "dndhelpdesk@gmail.com",
      phone: "188 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Wellington",
      email: "dndhelpdesk@gmail.com",
      phone: "189 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Westonaria",
      email: "dndhelpdesk@gmail.com",
      phone: "190 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Witbank Saveways",
      email: "dndhelpdesk@gmail.com",
      phone: "191 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Wynberg",
      email: "dndhelpdesk@gmail.com",
      phone: "192 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Yarona",
      email: "dndhelpdesk@gmail.com",
      phone: "193 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Debonairs Pizza Zevenwacht Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "194 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Anthos",
      email: "dndhelpdesk@gmail.com",
      phone: "195 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Bellville",
      email: "dndhelpdesk@gmail.com",
      phone: "196 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Benmore Gardens",
      email: "dndhelpdesk@gmail.com",
      phone: "197 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Brackencity",
      email: "dndhelpdesk@gmail.com",
      phone: "198 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Bronkhorstspruit",
      email: "dndhelpdesk@gmail.com",
      phone: "199 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Caltex Dundee",
      email: "dndhelpdesk@gmail.com",
      phone: "200 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Caltex Fortgale Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "201 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Celtis Ridge",
      email: "dndhelpdesk@gmail.com",
      phone: "202 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Chilli Lane",
      email: "dndhelpdesk@gmail.com",
      phone: "203 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Columbine Square",
      email: "dndhelpdesk@gmail.com",
      phone: "204 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Cradlestone Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "205 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Eldoraigne",
      email: "dndhelpdesk@gmail.com",
      phone: "206 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Elspark",
      email: "dndhelpdesk@gmail.com",
      phone: "207 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Engen Bisho",
      email: "dndhelpdesk@gmail.com",
      phone: "208 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Engen Bluewater Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "209 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Engen Ikwezi N2 Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "210 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Engen Queensburgh",
      email: "dndhelpdesk@gmail.com",
      phone: "211 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Flamwood Klerksdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "212 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Florida Road",
      email: "dndhelpdesk@gmail.com",
      phone: "213 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Fontainebleau Randburg",
      email: "dndhelpdesk@gmail.com",
      phone: "214 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Ga-Rankuwa",
      email: "dndhelpdesk@gmail.com",
      phone: "215 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Germiston Station Bazaar",
      email: "dndhelpdesk@gmail.com",
      phone: "216 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Gezina",
      email: "dndhelpdesk@gmail.com",
      phone: "217 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Ghandi & West",
      email: "dndhelpdesk@gmail.com",
      phone: "218 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Giyani Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "219 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Groblersdal",
      email: "dndhelpdesk@gmail.com",
      phone: "220 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Grosvenor Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "221 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Heidelberg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "222 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Key Largo Boksburg",
      email: "dndhelpdesk@gmail.com",
      phone: "223 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Komatipoort",
      email: "dndhelpdesk@gmail.com",
      phone: "224 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways La Montagne",
      email: "dndhelpdesk@gmail.com",
      phone: "225 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Lusikisiki",
      email: "dndhelpdesk@gmail.com",
      phone: "226 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Mall of the South",
      email: "dndhelpdesk@gmail.com",
      phone: "227 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Matlosana Mall Klerksdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "228 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Middelburg",
      email: "dndhelpdesk@gmail.com",
      phone: "229 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Middelburg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "230 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Midwater",
      email: "dndhelpdesk@gmail.com",
      phone: "231 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Mossel Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "232 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways New Market",
      email: "dndhelpdesk@gmail.com",
      phone: "233 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Newcastle Corner",
      email: "dndhelpdesk@gmail.com",
      phone: "234 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Nigel",
      email: "dndhelpdesk@gmail.com",
      phone: "235 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Noordheuwel",
      email: "dndhelpdesk@gmail.com",
      phone: "236 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Polofields",
      email: "dndhelpdesk@gmail.com",
      phone: "237 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Princess Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "238 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Queenswood",
      email: "dndhelpdesk@gmail.com",
      phone: "239 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Sasol Malelane",
      email: "dndhelpdesk@gmail.com",
      phone: "240 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Sasol Salt Rock",
      email: "dndhelpdesk@gmail.com",
      phone: "241 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Shell Monument Motors Paarl",
      email: "dndhelpdesk@gmail.com",
      phone: "242 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Springs Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "243 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Stellenbosch - Die Boord",
      email: "dndhelpdesk@gmail.com",
      phone: "244 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Stellenbosh - Eikestad Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "245 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Sterland",
      email: "dndhelpdesk@gmail.com",
      phone: "246 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Sun City",
      email: "dndhelpdesk@gmail.com",
      phone: "247 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Sunnyside",
      email: "dndhelpdesk@gmail.com",
      phone: "248 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Thavhani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "249 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways The Islands Food Court",
      email: "dndhelpdesk@gmail.com",
      phone: "250 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Three Rivers",
      email: "dndhelpdesk@gmail.com",
      phone: "251 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Tzaneen Lifestyle Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "252 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Vaal Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "253 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Vanderbijlpark Central",
      email: "dndhelpdesk@gmail.com",
      phone: "254 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Vorna Valley Midway Mews",
      email: "dndhelpdesk@gmail.com",
      phone: "255 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Watercrest Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "256 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Fishaways Zevenwacht Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "257 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Anthos",
      email: "dndhelpdesk@gmail.com",
      phone: "258 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Atteridgeville",
      email: "dndhelpdesk@gmail.com",
      phone: "259 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Bellville",
      email: "dndhelpdesk@gmail.com",
      phone: "260 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Benmore Gardens",
      email: "dndhelpdesk@gmail.com",
      phone: "261 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Birch Acres Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "262 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Bothasig",
      email: "dndhelpdesk@gmail.com",
      phone: "263 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Boulders",
      email: "dndhelpdesk@gmail.com",
      phone: "264 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Brackencity",
      email: "dndhelpdesk@gmail.com",
      phone: "265 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Bronkhorstspruit",
      email: "dndhelpdesk@gmail.com",
      phone: "266 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Caltex Dundee",
      email: "dndhelpdesk@gmail.com",
      phone: "267 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Caltex Maclear",
      email: "dndhelpdesk@gmail.com",
      phone: "268 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Caltex Northcrest",
      email: "dndhelpdesk@gmail.com",
      phone: "269 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Carlton Centre",
      email: "dndhelpdesk@gmail.com",
      phone: "270 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Celtis Ridge",
      email: "dndhelpdesk@gmail.com",
      phone: "271 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Centurion Lifestyle",
      email: "dndhelpdesk@gmail.com",
      phone: "272 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Chuma Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "273 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Columbine Square",
      email: "dndhelpdesk@gmail.com",
      phone: "274 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Cradlestone Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "275 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Dowerglen",
      email: "dndhelpdesk@gmail.com",
      phone: "276 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Durbanville",
      email: "dndhelpdesk@gmail.com",
      phone: "277 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Eldoraigne",
      email: "dndhelpdesk@gmail.com",
      phone: "278 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Elspark",
      email: "dndhelpdesk@gmail.com",
      phone: "279 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Bisho",
      email: "dndhelpdesk@gmail.com",
      phone: "280 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Bluewater Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "281 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Greytown",
      email: "dndhelpdesk@gmail.com",
      phone: "282 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Ikwezi N2 I Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "283 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Olympic Midrand",
      email: "dndhelpdesk@gmail.com",
      phone: "284 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Pretoria Motors",
      email: "dndhelpdesk@gmail.com",
      phone: "285 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Queensburgh",
      email: "dndhelpdesk@gmail.com",
      phone: "286 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Tembisa",
      email: "dndhelpdesk@gmail.com",
      phone: "287 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Engen Welgemoed",
      email: "dndhelpdesk@gmail.com",
      phone: "288 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Flamwood Klerksdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "289 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Florida Road",
      email: "dndhelpdesk@gmail.com",
      phone: "290 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Fontainebleau Randburg",
      email: "dndhelpdesk@gmail.com",
      phone: "291 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Ga-Rankuwa",
      email: "dndhelpdesk@gmail.com",
      phone: "292 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Ghandi & West",
      email: "dndhelpdesk@gmail.com",
      phone: "293 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Giyani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "294 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Glen Acres Drive Thru",
      email: "dndhelpdesk@gmail.com",
      phone: "295 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Grayston",
      email: "dndhelpdesk@gmail.com",
      phone: "296 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Grosvenor Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "297 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Heidelberg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "298 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Key Largo Boksburg",
      email: "dndhelpdesk@gmail.com",
      phone: "299 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Key West",
      email: "dndhelpdesk@gmail.com",
      phone: "300 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Knysna",
      email: "dndhelpdesk@gmail.com",
      phone: "301 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Kromboom",
      email: "dndhelpdesk@gmail.com",
      phone: "302 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Krugersdorp (Drive Thru)",
      email: "dndhelpdesk@gmail.com",
      phone: "303 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Kwa Guqa",
      email: "dndhelpdesk@gmail.com",
      phone: "304 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers KwaMnyandu Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "305 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers La Montagne",
      email: "dndhelpdesk@gmail.com",
      phone: "306 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Lemo Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "307 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Lichtenburg",
      email: "dndhelpdesk@gmail.com",
      phone: "308 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Long Street",
      email: "dndhelpdesk@gmail.com",
      phone: "309 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Lusikisiki",
      email: "dndhelpdesk@gmail.com",
      phone: "310 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mabopane Square",
      email: "dndhelpdesk@gmail.com",
      phone: "311 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Magalies View Rustenburg",
      email: "dndhelpdesk@gmail.com",
      phone: "312 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mall of The South",
      email: "dndhelpdesk@gmail.com",
      phone: "313 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mamms Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "314 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Marble Hall",
      email: "dndhelpdesk@gmail.com",
      phone: "315 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Masingita Crossing",
      email: "dndhelpdesk@gmail.com",
      phone: "316 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Matlosana Mall Klerksdorp",
      email: "dndhelpdesk@gmail.com",
      phone: "317 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mega City Mmabatho",
      email: "dndhelpdesk@gmail.com",
      phone: "318 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mhluzi Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "319 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Middelburg",
      email: "dndhelpdesk@gmail.com",
      phone: "320 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Middelburg Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "321 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Midwater",
      email: "dndhelpdesk@gmail.com",
      phone: "322 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Montague Gardens",
      email: "dndhelpdesk@gmail.com",
      phone: "323 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Mossel Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "324 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers New Market Drive Thru",
      email: "dndhelpdesk@gmail.com",
      phone: "325 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Nigel",
      email: "dndhelpdesk@gmail.com",
      phone: "326 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Noordheuwel",
      email: "dndhelpdesk@gmail.com",
      phone: "327 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Nquthu Plaza",
      email: "dndhelpdesk@gmail.com",
      phone: "328 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Okavango",
      email: "dndhelpdesk@gmail.com",
      phone: "329 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Paarl CBD",
      email: "dndhelpdesk@gmail.com",
      phone: "330 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Paarl Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "331 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Polofields",
      email: "dndhelpdesk@gmail.com",
      phone: "332 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Princess Crossing Drive Thru",
      email: "dndhelpdesk@gmail.com",
      phone: "333 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Queenswood",
      email: "dndhelpdesk@gmail.com",
      phone: "334 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Randfontein Drive Thru",
      email: "dndhelpdesk@gmail.com",
      phone: "335 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Riverside Square",
      email: "dndhelpdesk@gmail.com",
      phone: "336 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Rondebosch",
      email: "dndhelpdesk@gmail.com",
      phone: "337 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Delmas",
      email: "dndhelpdesk@gmail.com",
      phone: "338 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Groblersdal",
      email: "dndhelpdesk@gmail.com",
      phone: "339 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Kinross",
      email: "dndhelpdesk@gmail.com",
      phone: "340 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Malelane",
      email: "dndhelpdesk@gmail.com",
      phone: "341 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Salt Rock DT",
      email: "dndhelpdesk@gmail.com",
      phone: "342 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sasol Tzaneen",
      email: "dndhelpdesk@gmail.com",
      phone: "343 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sea Point",
      email: "dndhelpdesk@gmail.com",
      phone: "344 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Estcourt South",
      email: "dndhelpdesk@gmail.com",
      phone: "345 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Monument Motors Paarl",
      email: "dndhelpdesk@gmail.com",
      phone: "346 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Newcastle Drive Thru",
      email: "dndhelpdesk@gmail.com",
      phone: "347 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Plettenberg Bay",
      email: "dndhelpdesk@gmail.com",
      phone: "348 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Ultra City Mthatha",
      email: "dndhelpdesk@gmail.com",
      phone: "349 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Voorbaai",
      email: "dndhelpdesk@gmail.com",
      phone: "350 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Shell Wellington",
      email: "dndhelpdesk@gmail.com",
      phone: "351 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Silveroaks",
      email: "dndhelpdesk@gmail.com",
      phone: "352 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sky City Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "353 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Southgate Upper Level",
      email: "dndhelpdesk@gmail.com",
      phone: "354 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Springs Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "355 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Stellenbosch (Die Boord)",
      email: "dndhelpdesk@gmail.com",
      phone: "356 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Stellenbosch (Eikestad Mall)",
      email: "dndhelpdesk@gmail.com",
      phone: "357 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Stellenbosch (Simonsrust)",
      email: "dndhelpdesk@gmail.com",
      phone: "358 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sterland",
      email: "dndhelpdesk@gmail.com",
      phone: "359 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sun City",
      email: "dndhelpdesk@gmail.com",
      phone: "360 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sunninghill Chilli Lane",
      email: "dndhelpdesk@gmail.com",
      phone: "361 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Sunnyside",
      email: "dndhelpdesk@gmail.com",
      phone: "362 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Thavhani Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "363 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers The Colony",
      email: "dndhelpdesk@gmail.com",
      phone: "364 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers The Islands Food Court",
      email: "dndhelpdesk@gmail.com",
      phone: "365 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers The Village",
      email: "dndhelpdesk@gmail.com",
      phone: "366 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Three Rivers",
      email: "dndhelpdesk@gmail.com",
      phone: "367 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Total Naboomspruit",
      email: "dndhelpdesk@gmail.com",
      phone: "368 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Total Piet Retief Welgekozen",
      email: "dndhelpdesk@gmail.com",
      phone: "369 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Total Surfside Umdloti",
      email: "dndhelpdesk@gmail.com",
      phone: "370 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Total Wolmaranstad",
      email: "dndhelpdesk@gmail.com",
      phone: "371 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Tshwane Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "372 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Umhlanga Lagoon Drive DT",
      email: "dndhelpdesk@gmail.com",
      phone: "373 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Umphakathi Mall Randfontein",
      email: "dndhelpdesk@gmail.com",
      phone: "374 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Ushaka Marine World",
      email: "dndhelpdesk@gmail.com",
      phone: "375 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Vaal Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "376 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Vanderbijlpark Central",
      email: "dndhelpdesk@gmail.com",
      phone: "377 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Vangate Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "378 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Vorna Valley Midway Mews",
      email: "dndhelpdesk@gmail.com",
      phone: "379 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Vredendal",
      email: "dndhelpdesk@gmail.com",
      phone: "380 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Watercrest Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "381 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Watergate",
      email: "dndhelpdesk@gmail.com",
      phone: "382 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Westonaria",
      email: "dndhelpdesk@gmail.com",
      phone: "383 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Steers Zevenwacht Mall",
      email: "dndhelpdesk@gmail.com",
      phone: "384 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Wimpy Bram Fischer",
      email: "dndhelpdesk@gmail.com",
      phone: "385 000 000",
    },
    {
      name: "FM Manager",
      branch_company: "Wimpy Meyerton",
      email: "dndhelpdesk@gmail.com",
      phone: "386 000 000",
    },
  ],
  settings: [],
  filters: {
    startDate: new Date(
      new Date().getFullYear(),
      new Date().getMonth(),
      0
    ).toLocaleDateString(),
    endDate: new Date(
      new Date().getFullYear(),
      new Date().getMonth(),
      31
    ).toLocaleDateString(),
    brand: "",
    ticket_id: "",
    agent: "",
    category: "",
  },
  filteredTickets: [],
  frequentlyAsked: [],
};

export const TicketsSlice = createSlice({
  name: "Tickets",
  initialState,
  reducers: {
    addAllTickets: (state, action) => {
      state.allTickets = action.payload;
    },
    setContacts: (state, action) => {
      state.contacts = false === 1 ? action.payload : state.contacts;
    },
    loadSettings: (state, action) => {
      state.settings = action.payload;
    },
    setThreadMessage: (state, action) => {
      state.threadMessage = action.payload;
    },
    setThreadId: (state, action) => {
      state.threadId = action.payload;
    },
    loadFrequentlyAsked: (state, action) => {
      state.frequentlyAsked = action.payload;
    },
    filter: (state, action) => {
      state.filters = action.payload;
    },
    updateFilteredTickets: (state, action) => {
      state.filteredTickets = action.payload.sort(
        (a, b) =>
          new Date(a.due_date).getTime() - new Date(b.due_date).getTime()
      );
    },
  },
});

export const {
  addAllTickets,
  setContacts,
  loadSettings,
  setThreadMessage,
  setThreadId,
  loadFrequentlyAsked,
  filter,
  updateFilteredTickets,
} = TicketsSlice.actions;

export default TicketsSlice.reducer;
